### ISSUE TITLE
problem with build

### ISSUE THREAD

**Issue by moonhwi** [neje/ns3-network-performance-tool-v2#1]
I got lib/libns3.29-applications-debug.so：undefined referrence to‘ns3::operator<<(std::ostream&, ns3::WifiMode const&)’collect2: error: ld returned 1 exit status
 do you have idea about how to fix this problem.
(finished ./waf distclean,and it happened when run ./waf build)

**Comment by neje** [comment]
I'm sorry but I'm on holiday right now until August 2nd and I do not have an ns-3 simulator at hand. It will be my pleasure to try to help after my return from vacation.
As far as I recall, I did not use the operator "operator << (std :: ostream &, ns3 :: WifiMode const &)" anywhere in the code, but I will do my best to find out what caused the bug.

**Comment by moonhwi** [comment]
Thanks for your reply,I reconfigure my waf and rebuild with build.py ,and then everything went well.I guess something goes wrong with my pythonbinding .Happy  holiday .Cheers.
